server:
  port: 8008
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shoptestdb?characterEncoding=utf8
    username: smuser
    password: 111111

mybatis:
  type-aliases-package: edu.sm.shoptemplatetest.dto
#  sql문을 넣는곳
  mapper-locations: classpath:/mapper/*.xml
  configuration:
#    underscore를 camel style로 바꾸겠다 자동으로 매핑해준다
      map-underscore-to-camel-case: true

logging:
  level:
    root: info

app:
  dir:  #절대경로다 스프링프레임워크 밖에 있기때문
    imgsdir: file:///C:/test/imgs/     # 화면 출력 용
    uploadimgsdir: C:/test/imgs/    # 파일 Write 용